name: vins-neo-release

services:
  release:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile.rpi
      target: pre-release
      args:
        DEBIAN_SUITE: trixie
        ROS_DISTRO: jazzy
        IROS_VERSION: 0.1.1
        IROS_DEB_VERSION: 0.1.1-1+deb13
        IROS_SHA256: 62ef93734ae588cb5f342e902556d4cfa7b21de071bfedfe5b72c5431e42fe25
        CV_BRIDGE_REF: f5b738d9694f0cee5904440d03912fc249943f8a
        PACKAGE_VERSION: ${PACKAGE_VERSION:-1.0.1.7}
      platforms:
        - linux/arm64
    image: vins-neo:debian13-arm64-pre-release
